# https://github.com/ansible/ansible/issues/68536
#- name: Populate systemd service facts
#  ansible.builtin.service_facts:

- name: Check if http-echo exists
  stat:
    path: /etc/systemd/system/http-echo.service
  register: service_status

- name: Stop http-echo
  systemd:
    name: http-echo
    state: stopped
  when: service_status.stat.exists

- name: Remove previous download files
  file:
    path: /tmp/pipy-0.30.0-70-generic_linux-x86_64.tar.gz
    state: absent

- name: Download pipy
  get_url:
    url: https://pipy-oss-1255617643.cos-website.ap-beijing.myqcloud.com/repo/pipy/x86_64/binary/pipy-0.30.0-70-generic_linux-x86_64.tar.gz
    dest: /tmp/pipy-0.30.0-70-generic_linux-x86_64.tar.gz

- name: Decompress tarball
  unarchive:
    remote_src: yes
    src: /tmp/pipy-0.30.0-70-generic_linux-x86_64.tar.gz
    dest: /usr/local/bin

- name: Create pipy user
  user:
    name: pipy
    system: yes

- name: Create start script
  template:
    src: pipy-start.sh.j2
    dest: /usr/bin/pipy-start.sh
    mode: 0755

- name: Configure systemd
  template:
    src: pipy.service.j2
    dest: /etc/systemd/system/pipy.service
  notify:
    - reload systemd

- name: Configure pipy
  template:
    src: main.js.j2
    dest: /etc/pipy/main.js
  notify:
    - restart pipy

- name: Start pipy
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: pipy
