- name: Set kernel options
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    sysctl_set: yes
    reload: yes
    state: present
  with_items:
    - {name: "net.ipv4.ip_local_port_range", value: "1024 65000"}
    - {name: "net.ipv4.ip_local_reserved_ports", value: "8080,18080,28080,38080,48080"}
    - {name: "net.ipv4.tcp_timestamps", value: "0"}

- name: Set ulimit
  pam_limits:
    domain: "*"
    limit_type: '-'
    limit_item: "nofile"
    value: 655360
