- name: Remove previous download files
  file:
    path: "/tmp/{{pipy_binary_package}}"
    state: absent

- name: Download pipy
  get_url:
    url: "https://pipy-oss-1255617643.cos-website.ap-beijing.myqcloud.com/repo/pipy/{{ansible_architecture}}/binary/{{pipy_binary_package}}"
    dest: "/tmp/{{pipy_binary_package}}"

- name: Decompress tarball
  unarchive:
    remote_src: yes
    src: "/tmp/{{pipy_binary_package}}"
    dest: /usr/local/bin

- name: Create pipy user
  user:
    name: pipy
    system: yes

- name: Create working dir
  file:
    state: directory
    path: /etc/pipy
    owner: pipy

- name: Create start script
  template:
    src: pipy-start.sh.j2
    dest: /usr/bin/pipy-start.sh
    mode: 0755

- name: Set repo url
  tags: repo
  set_fact:
    pipy_config_uri: "http://{{hostvars[groups['pipy_repo'][0]]['ansible_default_ipv4']['address']}}:{{repo_port|default('6060')}}/repo/benchmark/{{role}}/"

- name: Configure systemd
  template:
    src: pipy.service.j2
    dest: /etc/systemd/system/pipy.service
  notify:
    - reload systemd

- name: Start pipy
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: pipy
  tags: repo

- name: Set balancer.json
  tags: repo
  local_action:
    module: ansible.builtin.template
    src: balancer.json.j2
    dest: pipy-repo/proxy/config/balancer.json

- name: Init repo
  tags: repo
  local_action:
    module: ansible.builtin.shell ./init-repo.sh "{{hostvars[groups['pipy_repo'][0]]['ansible_default_ipv4']['address']}}:{{repo_port|default('6060')}}"
    args:
      chdir: pipy-repo
  when: 'role == "repo"'
