---
- hosts: all
  gather_facts: yes
  become: yes
  tags: [always]

- hosts: all
  gather_facts: yes
  become: yes
  tags: [init]

  roles:
    - os-setup

- hosts: client_group
  gather_facts: yes
  become: yes
  tags: [client]

  roles:
    - fortio
    - wrk2
    - jmeter

- hosts: upstream_group
  gather_facts: yes
  become: yes
  tags: [upstream]

  roles:
    - role: 'http-echo'
      tags: 'echo'
      when: mode is not defined or mode != 'payload'

    - role: 'pipy-hello'
      tags: 'pipy-hello'
      when: mode is defined and mode == 'payload'

- hosts: proxy_group
  gather_facts: yes
  become: yes
  tags: [proxy]

  roles:
  - {role: 'nginx', tags: 'nginx'}
  - {role: 'haproxy', tags: 'haproxy'}
  - {role: 'pipy', tags: 'pipy'}
  - {role: 'envoy', tags: 'envoy'}
