---
- hosts: all
  gather_facts: yes
  become: yes
  tags: [always]

  tasks:
    - name: Define pipy repo
      add_host:
        groups:
          - pipy_repo
        name: "{{groups['client_group'][0]}}"
      when: "groups['pipy_repo']|length == 0"

- hosts: all
  gather_facts: yes
  become: yes
  tags:
    - init
    - always

  roles:
    - os-setup

- hosts: client_group
  gather_facts: yes
  become: yes
  tags: [client]

  roles:
    - fortio
    - wrk2
    - jmeter

- hosts: pipy_repo
  gather_facts: yes
  become: yes

  roles:
    - role: pipy
      tags: pipy

- hosts: upstream_group
  gather_facts: yes
  become: yes
  tags: [upstream]

  roles:
    - role: 'pipy'
      tags: 'pipy'

- hosts: proxy_group
  gather_facts: yes
  become: yes
  tags: [proxy]

  roles:
  - {role: 'nginx', tags: 'nginx'}
  - {role: 'haproxy', tags: 'haproxy'}
  - {role: 'pipy', tags: 'pipy'}
  - {role: 'envoy', tags: 'envoy'}
